services:
  postgres:
    image: postgres:16
    container_name: ms-email-db
    environment:
      POSTGRES_DB: ms_email_ms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - emaildata:/var/lib/postgresql/data

volumes:
  emaildata: