services:
  postgres:
    image: postgres:16
    container_name: ms-user-db
    environment:
      POSTGRES_DB: ms-user-ms
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: postgres-password
    ports:
      - "5435:5432"
    volumes:
      - userdata:/var/lib/postgresql/data
volumes:
  userdata: